# Generated by Django 3.2.12 on 2023-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
