# Generated by Django 3.2.12 on 2023-06-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
